# This is a basic workflow to help you get started with Actions

name: API
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: set up node.js
      uses: actions/setup-node@v4.3.0
      with:
        node-version: '20'

    - name: Install depedencie
      run: npm install
    - name: Run application
      run: node ./Bot/gemini.js
    - name: Run calculation fish
      run: node ./Bot/Interaction.js
        